// Folder: IO/Devices

#include "EnginePCH.h"
#include "WinKeyboardDevice.h"

#ifdef BP_PLATFORM_WINDOWS

WinKeyboardDevice::WinKeyboardDevice(InputDeviceIdentifier identifier)
	: KeyboardInputDevice(identifier)
{}

void WinKeyboardDevice::Update()
{
	// Checking if the focused window is one of our windows
	if (GetWindowThreadProcessId(GetFocus(), NULL) == GetCurrentThreadId())
	{
		for (uint i = 0; i < (uint)KeyboardControl::_COUNT; ++i)
		{
			KeyboardControl action = (KeyboardControl)i;
			SetState(i, (bool)GetAsyncKeyState(ConvertInputAction(action)));
		}
	}
}

uint WinKeyboardDevice::ConvertInputAction(KeyboardControl action) const
{
	switch (action)
	{
	case KeyboardControl::KEYBOARD_BACKSPACE:
		return VK_BACK;
	case KeyboardControl::KEYBOARD_TAB:
		return VK_TAB;
	case KeyboardControl::KEYBOARD_CLEAR:
		return VK_CLEAR;
	case KeyboardControl::KEYBOARD_RETURN:
		return VK_RETURN;
	case KeyboardControl::KEYBOARD_PAUSE:
		return VK_PAUSE;
	case KeyboardControl::KEYBOARD_CAPSLOCK:
		return VK_CAPITAL;
	case KeyboardControl::KEYBOARD_ESCAPE:
		return VK_ESCAPE;
	case KeyboardControl::KEYBOARD_SPACE:
		return VK_SPACE;
	case KeyboardControl::KEYBOARD_PAGE_UP:
		return VK_PRIOR;
	case KeyboardControl::KEYBOARD_PAGE_DOWN:
		return VK_NEXT;
	case KeyboardControl::KEYBOARD_END:
		return VK_END;
	case KeyboardControl::KEYBOARD_HOME:
		return VK_HOME;
	case KeyboardControl::KEYBOARD_LEFT_ARROW:
		return VK_LEFT;
	case KeyboardControl::KEYBOARD_RIGHT_ARROW:
		return VK_RIGHT;
	case KeyboardControl::KEYBOARD_UP_ARROW:
		return VK_UP;
	case KeyboardControl::KEYBOARD_DOWN_ARROW:
		return VK_DOWN;
	case KeyboardControl::KEYBOARD_SELECT:
		return VK_SELECT;
	case KeyboardControl::KEYBOARD_PRINT:
		return VK_PRINT;
	case KeyboardControl::KEYBOARD_EXECUTE:
		return VK_EXECUTE;
	case KeyboardControl::KEYBOARD_PRINT_SCREEN:
		return VK_SNAPSHOT;
	case KeyboardControl::KEYBOARD_INSERT:
		return VK_INSERT;
	case KeyboardControl::KEYBOARD_DELETE:
		return VK_DELETE;
	case KeyboardControl::KEYBOARD_HELP:
		return VK_HELP;
	case KeyboardControl::KEYBOARD_0:
		return 0x30;
	case KeyboardControl::KEYBOARD_1:
		return 0x31;
	case KeyboardControl::KEYBOARD_2:
		return 0x32;
	case KeyboardControl::KEYBOARD_3:
		return 0x33;
	case KeyboardControl::KEYBOARD_4:
		return 0x34;
	case KeyboardControl::KEYBOARD_5:
		return 0x35;
	case KeyboardControl::KEYBOARD_6:
		return 0x36;
	case KeyboardControl::KEYBOARD_7:
		return 0x37;
	case KeyboardControl::KEYBOARD_8:
		return 0x38;
	case KeyboardControl::KEYBOARD_9:
		return 0x39;
	case KeyboardControl::KEYBOARD_A:
		return 0x41;
	case KeyboardControl::KEYBOARD_B:
		return 0x42;
	case KeyboardControl::KEYBOARD_C:
		return 0x43;
	case KeyboardControl::KEYBOARD_D:
		return 0x44;
	case KeyboardControl::KEYBOARD_E:
		return 0x45;
	case KeyboardControl::KEYBOARD_F:
		return 0x46;
	case KeyboardControl::KEYBOARD_G:
		return 0x47;
	case KeyboardControl::KEYBOARD_H:
		return 0x48;
	case KeyboardControl::KEYBOARD_I:
		return 0x49;
	case KeyboardControl::KEYBOARD_J:
		return 0x4A;
	case KeyboardControl::KEYBOARD_K:
		return 0x4B;
	case KeyboardControl::KEYBOARD_L:
		return 0x4C;
	case KeyboardControl::KEYBOARD_M:
		return 0x4D;
	case KeyboardControl::KEYBOARD_N:
		return 0x4E;
	case KeyboardControl::KEYBOARD_O:
		return 0x4F;
	case KeyboardControl::KEYBOARD_P:
		return 0x50;
	case KeyboardControl::KEYBOARD_Q:
		return 0x51;
	case KeyboardControl::KEYBOARD_R:
		return 0x52;
	case KeyboardControl::KEYBOARD_S:
		return 0x53;
	case KeyboardControl::KEYBOARD_T:
		return 0x54;
	case KeyboardControl::KEYBOARD_U:
		return 0x55;
	case KeyboardControl::KEYBOARD_V:
		return 0x56;
	case KeyboardControl::KEYBOARD_W:
		return 0x57;
	case KeyboardControl::KEYBOARD_X:
		return 0x58;
	case KeyboardControl::KEYBOARD_Y:
		return 0x59;
	case KeyboardControl::KEYBOARD_Z:
		return 0x5A;
	case KeyboardControl::KEYBOARD_LWINDOWS:
		return VK_LWIN;
	case KeyboardControl::KEYBOARD_RWINDOWS:
		return VK_RWIN;
	case KeyboardControl::KEYBOARD_APPS:
		return VK_APPS;
	case KeyboardControl::KEYBOARD_SLEEP:
		return VK_SLEEP;
	case KeyboardControl::KEYBOARD_NUMPAD0:
		return VK_NUMPAD0;
	case KeyboardControl::KEYBOARD_NUMPAD1:
		return VK_NUMPAD1;
	case KeyboardControl::KEYBOARD_NUMPAD2:
		return VK_NUMPAD2;
	case KeyboardControl::KEYBOARD_NUMPAD3:
		return VK_NUMPAD3;
	case KeyboardControl::KEYBOARD_NUMPAD4:
		return VK_NUMPAD4;
	case KeyboardControl::KEYBOARD_NUMPAD5:
		return VK_NUMPAD5;
	case KeyboardControl::KEYBOARD_NUMPAD6:
		return VK_NUMPAD6;
	case KeyboardControl::KEYBOARD_NUMPAD7:
		return VK_NUMPAD7;
	case KeyboardControl::KEYBOARD_NUMPAD8:
		return VK_NUMPAD8;
	case KeyboardControl::KEYBOARD_NUMPAD9:
		return VK_NUMPAD9;
	case KeyboardControl::KEYBOARD_MULTIPLY:
		return VK_MULTIPLY;
	case KeyboardControl::KEYBOARD_ADD:
		return VK_ADD;
	case KeyboardControl::KEYBOARD_SEPARATOR:
		return VK_SEPARATOR;
	case KeyboardControl::KEYBOARD_SUBTRACT:
		return VK_SUBTRACT;
	case KeyboardControl::KEYBOARD_DECIMAL:
		return VK_DECIMAL;
	case KeyboardControl::KEYBOARD_DIVIDE:
		return VK_DIVIDE;
	case KeyboardControl::KEYBOARD_F1:
		return VK_F1;
	case KeyboardControl::KEYBOARD_F2:
		return VK_F2;
	case KeyboardControl::KEYBOARD_F3:
		return VK_F3;
	case KeyboardControl::KEYBOARD_F4:
		return VK_F4;
	case KeyboardControl::KEYBOARD_F5:
		return VK_F5;
	case KeyboardControl::KEYBOARD_F6:
		return VK_F6;
	case KeyboardControl::KEYBOARD_F7:
		return VK_F7;
	case KeyboardControl::KEYBOARD_F8:
		return VK_F8;
	case KeyboardControl::KEYBOARD_F9:
		return VK_F9;
	case KeyboardControl::KEYBOARD_F10:
		return VK_F10;
	case KeyboardControl::KEYBOARD_F11:
		return VK_F11;
	case KeyboardControl::KEYBOARD_F12:
		return VK_F12;
	case KeyboardControl::KEYBOARD_F13:
		return VK_F13;
	case KeyboardControl::KEYBOARD_F14:
		return VK_F14;
	case KeyboardControl::KEYBOARD_F15:
		return VK_F15;
	case KeyboardControl::KEYBOARD_F16:
		return VK_F16;
	case KeyboardControl::KEYBOARD_F17:
		return VK_F17;
	case KeyboardControl::KEYBOARD_F18:
		return VK_F18;
	case KeyboardControl::KEYBOARD_F19:
		return VK_F19;
	case KeyboardControl::KEYBOARD_F20:
		return VK_F20;
	case KeyboardControl::KEYBOARD_F21:
		return VK_F21;
	case KeyboardControl::KEYBOARD_F22:
		return VK_F22;
	case KeyboardControl::KEYBOARD_F23:
		return VK_F23;
	case KeyboardControl::KEYBOARD_F24:
		return VK_F24;
	case KeyboardControl::KEYBOARD_NUMLOCK:
		return VK_NUMLOCK;
	case KeyboardControl::KEYBOARD_SCROLLLOCK:
		return VK_SCROLL;
	case KeyboardControl::KEYBOARD_LSHIFT:
		return VK_LSHIFT;
	case KeyboardControl::KEYBOARD_RSHIFT:
		return VK_RSHIFT;
	case KeyboardControl::KEYBOARD_LCONTROL:
		return VK_LCONTROL;
	case KeyboardControl::KEYBOARD_RCONTROL:
		return VK_RCONTROL;
	case KeyboardControl::KEYBOARD_LALT:
		return VK_LMENU;
	case KeyboardControl::KEYBOARD_RALT:
		return VK_RMENU;
	case KeyboardControl::KEYBOARD_BROWSER_BACK:
		return VK_BROWSER_BACK;
	case KeyboardControl::KEYBOARD_BROWSER_FORWARD:
		return VK_BROWSER_FORWARD;
	case KeyboardControl::KEYBOARD_BROWSER_REFRESH:
		return VK_BROWSER_REFRESH;
	case KeyboardControl::KEYBOARD_BROWSER_STOP:
		return VK_BROWSER_STOP;
	case KeyboardControl::KEYBOARD_BROWSER_SEARCH:
		return VK_BROWSER_SEARCH;
	case KeyboardControl::KEYBOARD_BROWSER_FAVORITES:
		return VK_BROWSER_FAVORITES;
	case KeyboardControl::KEYBOARD_BROWSER_HOME:
		return VK_BROWSER_HOME;
	case KeyboardControl::KEYBOARD_VOLUME_MUTE:
		return VK_VOLUME_MUTE;
	case KeyboardControl::KEYBOARD_VOLUME_DOWN:
		return VK_VOLUME_DOWN;
	case KeyboardControl::KEYBOARD_VOLUME_UP:
		return VK_VOLUME_UP;
	case KeyboardControl::KEYBOARD_MEDIA_NEXT:
		return VK_MEDIA_NEXT_TRACK;
	case KeyboardControl::KEYBOARD_MEDIA_PREVIOUS:
		return VK_MEDIA_PREV_TRACK;
	case KeyboardControl::KEYBOARD_MEDIA_STOP:
		return VK_MEDIA_STOP;
	case KeyboardControl::KEYBOARD_MEDIA_PLAY_PAUSE:
		return VK_MEDIA_PLAY_PAUSE;
	case KeyboardControl::KEYBOARD_LAUNCH_MAIL:
		return VK_LAUNCH_MAIL;
	case KeyboardControl::KEYBOARD_LAUNCH_MEDIA_SELECT:
		return VK_LAUNCH_MEDIA_SELECT;
	case KeyboardControl::KEYBOARD_LAUNCH_APP1:
		return VK_LAUNCH_APP1;
	case KeyboardControl::KEYBOARD_LAUNCH_APP2:
		return VK_LAUNCH_APP2;
	case KeyboardControl::KEYBOARD_OEM_COLON_SEMICOLON:
		return VK_OEM_1;
	case KeyboardControl::KEYBOARD_OEM_PLUS:
		return VK_OEM_PLUS;
	case KeyboardControl::KEYBOARD_OEM_COMMA:
		return VK_OEM_COMMA;
	case KeyboardControl::KEYBOARD_OEM_MINUS:
		return VK_OEM_MINUS;
	case KeyboardControl::KEYBOARD_OEM_PERIOD:
		return VK_OEM_PERIOD;
	case KeyboardControl::KEYBOARD_OEM_SLASH_QUESTIONMARK:
		return VK_OEM_2;
	case KeyboardControl::KEYBOARD_OEM_TILDE:
		return VK_OEM_3;
	case KeyboardControl::KEYBOARD_OEM_BRACKETS_OPEN:
		return VK_OEM_4;
	case KeyboardControl::KEYBOARD_OEM_BACKSLASH_PIPE:
		return VK_OEM_5;
	case KeyboardControl::KEYBOARD_OEM_BRACKETS_CLOSE:
		return VK_OEM_6;
	case KeyboardControl::KEYBOARD_OEM_QUOTES:
		return VK_OEM_7;
	case KeyboardControl::KEYBOARD_OEM_ANGLE_BRACKET:
		return VK_OEM_102;
	}

	LOG_ERROR("Unknown InputAction keyboard key, key=%d", (uint)action);
	return UINT_MAX;
}

#endif